# Generated by Django 5.2.7 on 2025-10-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mcq_question', models.TextField(blank=True, null=True)),
                ('mcq_options', models.JSONField(blank=True, null=True)),
                ('mcq_correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
