# Generated by Django 5.2.7 on 2025-11-18 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='mcq_correct_answer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='mcq_options',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='mcq_question',
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('CONTENT', 'Content'), ('ASSESSMENT', 'Assessment')], default='CONTENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Module 1 Test', max_length=255)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
