# Generated by Django 5.2.7 on 2026-01-20 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_explanationattempt_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationattempt',
            name='transcript_hash',
            field=models.CharField(db_index=True, default='legacy', help_text='SHA256 hash of normalized transcript', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explanationattempt',
            name='transcript',
            field=models.TextField(help_text='User provided explanation transcript'),
        ),
        migrations.AddIndex(
            model_name='explanationattempt',
            index=models.Index(fields=['user', 'lesson', 'transcript_hash'], name='core_explan_user_id_439da7_idx'),
        ),
    ]
